SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [ods].[carga_transacciones]
AS
BEGIN

DECLARE @date NVARCHAR(8),
		@hora NVARCHAR(8);

SET @date = (select date from ctl.wrk01);
SET @hora = (select hora from ctl.wrk02);

--truncates
truncate table ods.W1_TRANSACCION   ;
/* no se trunca bds.TRANSACCION (transaccion principal) */


INSERT INTO ods.W1_TRANSACCION
SELECT CAB.CODIGODEPARTICIPANTE AS  CODIGODEPARTICIPANTE,
       CAB.CODIGODELOCAL        AS  CODIGODELOCAL       ,
       CAB.NUMTARJETABONUS      AS  NUMTARJETABONUS     ,
       CAB.FECHATRANSACCIONS02  AS  FECHATRANSACCION_CAB,
       CAB.HORATRANSACCIONS02   AS  HORATRANSACCION_CAB,
       CAB.NROPOS               AS  NROPOS              ,
       CAB.NROTRNPOS            AS  NROTRNPOS           ,
       CAB.MONTOTOTAL           AS  MONTOTOTAL          ,
       CAB.SIGNO_MT             AS  SIGNO_MT            ,
       CAB.PTOSACUMULADOS       AS  PTOSACUMULADOS      ,
       CAB.SIGNO_PA             AS  SIGNO_PA            ,
       CAB.FECHAASIGNACIONS52   AS  FECHAASIGNACION_CAB ,
       CAB.CODIGODEPROMOCION    AS  CODIGODEPROMOCION   ,
       IIF(PRM.DESCRIPCIONS51 IS NOT NULL, PRM.DESCRIPCIONS51, 'SIN DESCRIPCION')  AS DESCRIPCION_PRM,
       CAB.TIPODETRANSACCION    AS  TIPODETRANSACCION   ,
       CAB.NOMBREDEALER         AS  NOMBREDEALER        ,
       CAB.IDTRX                AS  IDTRX               ,
       IIF(DET.SEC IS NOT NULL, DET.SEC, '000')  AS SEC,
       IIF(DET.PLU IS NOT NULL, DET.PLU, '00000000000000')  AS PLU,
       DET.CANTIDAD    ,
       DET.MONTOPARCIAL,
       DET.SIGNO_MP
  FROM ods.W4_52_TCAAMMDD_CWN AS CAB
         LEFT JOIN ods.W4_53_TDAAMMDD_CWN AS DET ON CAB.IDTRX = DET.IDTRX
         LEFT JOIN ods.W4_51_TAAAMMDD_CWN AS PRM ON CAB.CODIGODEPROMOCION = PRM.CODIGODEPROMOCION;

--wa de detalle transaccion codigos nulos
UPDATE ods.W1_TRANSACCION SET SEC = '000' WHERE SEC IS NULL;
UPDATE ods.W1_TRANSACCION SET PLU = '00000000000000' WHERE PLU IS NULL;

DELETE ods.W1_TRANSACCION WHERE CODIGODEPARTICIPANTE = '';
DELETE ods.W1_TRANSACCION WHERE CODIGODEPARTICIPANTE IS NULL;
DELETE ods.W1_TRANSACCION WHERE SIGNO_MP IS NULL;


INSERT INTO bds.TRANSACCION
SELECT CODIGODEPARTICIPANTE,
       CODIGODELOCAL       ,
       NUMTARJETABONUS     ,
       FECHATRANSACCION_CAB,
       HORATRANSACCION_CAB ,
       CONCAT(LEFT(HORATRANSACCION_CAB,2),':',
              CASE
                  WHEN SUBSTRING ( HORATRANSACCION_CAB ,4 , 2 )*1  >= 0  AND SUBSTRING ( HORATRANSACCION_CAB ,4 , 2 )*1 < 15 THEN '00'
                  WHEN SUBSTRING ( HORATRANSACCION_CAB ,4 , 2 )*1  >= 15 AND SUBSTRING ( HORATRANSACCION_CAB ,4 , 2 )*1 < 30 THEN '15'
                  WHEN SUBSTRING ( HORATRANSACCION_CAB ,4 , 2 )*1  >= 30 AND SUBSTRING ( HORATRANSACCION_CAB ,4 , 2 )*1 < 45 THEN '30'
                  ELSE '45'
              END) as  HORATRANSSECCION_CAB,
       NROPOS              ,
       NROTRNPOS           ,
       MONTOTOTAL          ,
       SIGNO_MT            ,
       IIF([SIGNO_MT]='+', CAST ( MONTOTOTAL AS FLOAT )/100, (CAST ( MONTOTOTAL AS FLOAT )*-1)/100) AS MONTOTOTALNUM,
       PTOSACUMULADOS      ,
       SIGNO_PA            ,
       IIF([SIGNO_PA]='+', CAST ( PTOSACUMULADOS AS FLOAT )/100, (CAST ( PTOSACUMULADOS AS FLOAT )*-1)/100) AS PTOSACUMULADOSNUM,
       FECHAASIGNACION_CAB ,
       CODIGODEPROMOCION   ,
       DESCRIPCION_PRM     ,
       '20200825',
       '20200825',
       TIPODETRANSACCION   ,
       NOMBREDEALER        ,
       '20200825',
       '20200825',
       IDTRX       ,
       SEC         ,
       PLU         ,
       CANTIDAD    ,
       CAST ( CANTIDAD AS FLOAT )/1000 AS CANTIDADNUM  , --validar!
       MONTOPARCIAL,
       SIGNO_MP,
       IIF([SIGNO_MP]='+', CAST ( MONTOPARCIAL AS FLOAT )/100, (CAST ( MONTOPARCIAL AS FLOAT )*-1)/100) AS MONTOPARCIALNUM,
       '20200825',
       '20200825',
       @date as fecha,
       @hora as hora
FROM ods.W1_TRANSACCION;

END
GO