SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [stg].[carga_maestros]
AS
BEGIN

DECLARE @date NVARCHAR(8),
		@hora NVARCHAR(8);

SET @date = (select date from ctl.wrk01);
SET @hora = (select hora from ctl.wrk02);

--truncates

TRUNCATE TABLE stg.S01_CLTE_PJ_TXT   ;
TRUNCATE TABLE stg.S02_CLTE_PN_TXT   ;
TRUNCATE TABLE stg.S03_CLTUNIF_TXT   ;
TRUNCATE TABLE stg.S04_DIRECC_TXT    ;
TRUNCATE TABLE stg.S05_EMAIL_TXT     ;
TRUNCATE TABLE stg.S06_EMANOCON_TXT  ;
TRUNCATE TABLE stg.S07_HIJOS_TXT     ;
TRUNCATE TABLE stg.S08_TARJETA_TXT   ;
TRUNCATE TABLE stg.S09_TELEF_TXT     ;
TRUNCATE TABLE stg.S10_TLFNOCON_TXT  ;

--ods maestros
TRUNCATE TABLE ods.W1_01_CLTE_PJ_TXT ;
TRUNCATE TABLE ods.W1_02_CLTE_PN_TXT ;
TRUNCATE TABLE ods.W1_03_CLTUNIF_TXT ;
TRUNCATE TABLE ods.W1_04_DIRECC_TXT  ;
TRUNCATE TABLE ods.W1_05_EMAIL_TXT   ;
TRUNCATE TABLE ods.W1_06_EMANOCON_TXT;
TRUNCATE TABLE ods.W1_07_HIJOS_TXT   ;
TRUNCATE TABLE ods.W1_08_TARJETA_TXT ;
TRUNCATE TABLE ods.W1_09_TELEF_TXT   ;
TRUNCATE TABLE ods.W1_10_TLFNOCON_TXT;

TRUNCATE TABLE ods.W2_01_CLTE_PJ_TXT ;
TRUNCATE TABLE ods.W2_02_CLTE_PN_TXT ;
TRUNCATE TABLE ods.W2_03_CLTUNIF_TXT ;
TRUNCATE TABLE ods.W2_04_DIRECC_TXT  ;
TRUNCATE TABLE ods.W2_05_EMAIL_TXT   ;
TRUNCATE TABLE ods.W2_06_EMANOCON_TXT;
TRUNCATE TABLE ods.W2_07_HIJOS_TXT   ;
TRUNCATE TABLE ods.W2_08_TARJETA_TXT ;
TRUNCATE TABLE ods.W2_09_TELEF_TXT   ;
TRUNCATE TABLE ods.W2_10_TLFNOCON_TXT;

--se asume que 01 y 02 son consistentes
TRUNCATE TABLE ods.W3_03_CLTUNIF_TXT ;
TRUNCATE TABLE ods.W3_04_DIRECC_TXT  ;
TRUNCATE TABLE ods.W3_05_EMAIL_TXT   ;
TRUNCATE TABLE ods.W3_06_EMANOCON_TXT;
TRUNCATE TABLE ods.W3_07_HIJOS_TXT   ;
TRUNCATE TABLE ods.W3_09_TELEF_TXT   ;
TRUNCATE TABLE ods.W3_10_TLFNOCON_TXT;

--inserts maestros
BULK INSERT stg.S01_CLTE_PJ_TXT  FROM 'e:\bi\biclbo\ftp\bandeja\CLTE_PJ.TXT' WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'Char');
BULK INSERT stg.S02_CLTE_PN_TXT  FROM 'e:\bi\biclbo\ftp\bandeja\CLTE_PN.TXT' WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'Char');
BULK INSERT stg.S03_CLTUNIF_TXT  FROM 'e:\bi\biclbo\ftp\bandeja\CLTUNIF.TXT' WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'Char');
BULK INSERT stg.S04_DIRECC_TXT   FROM 'e:\bi\biclbo\ftp\bandeja\DIRECC.TXT' WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'Char');
BULK INSERT stg.S05_EMAIL_TXT    FROM 'e:\bi\biclbo\ftp\bandeja\EMAIL.TXT' WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'Char');
BULK INSERT stg.S06_EMANOCON_TXT FROM 'e:\bi\biclbo\ftp\bandeja\EMANOCON.TXT' WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'Char');
BULK INSERT stg.S07_HIJOS_TXT    FROM 'e:\bi\biclbo\ftp\bandeja\HIJOS.TXT' WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'Char');
BULK INSERT stg.S08_TARJETA_TXT  FROM 'e:\bi\biclbo\ftp\bandeja\TARJETA.TXT' WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'Char');
BULK INSERT stg.S09_TELEF_TXT    FROM 'e:\bi\biclbo\ftp\bandeja\TELEF.TXT' WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'Char');
BULK INSERT stg.S10_TLFNOCON_TXT FROM 'e:\bi\biclbo\ftp\bandeja\TLFNOCON.TXT' WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'Char');


INSERT INTO ods.W1_01_CLTE_PJ_TXT
SELECT SUBSTRING(TRAMA,1,10),
       '02',
       SUBSTRING(TRAMA,11,4) ,
       SUBSTRING(TRAMA,15,15),
       SUBSTRING(TRAMA,30,50),
       SUBSTRING(TRAMA,80,8) ,
       SUBSTRING(TRAMA,88,8) ,
       SUBSTRING(TRAMA,96,8)
  FROM stg.S01_CLTE_PJ_TXT;

INSERT INTO ods.W1_02_CLTE_PN_TXT
SELECT SUBSTRING(TRAMA,1,10) ,
       SUBSTRING(TRAMA,11,2) ,
       SUBSTRING(TRAMA,13,4) ,
       SUBSTRING(TRAMA,17,15),
       SUBSTRING(TRAMA,32,11),
       SUBSTRING(TRAMA,43,100),
       SUBSTRING(TRAMA,143,50),
       SUBSTRING(TRAMA,193,50),
       SUBSTRING(TRAMA,243,8),
       SUBSTRING(TRAMA,251,1),
       SUBSTRING(TRAMA,252,1),
       SUBSTRING(TRAMA,253,1),
       SUBSTRING(TRAMA,254,1),
       SUBSTRING(TRAMA,255,1),
       SUBSTRING(TRAMA,256,1),
       SUBSTRING(TRAMA,257,1),
       SUBSTRING(TRAMA,258,1),
       SUBSTRING(TRAMA,259,8),
       SUBSTRING(TRAMA,267,8),
       SUBSTRING(TRAMA,275,8)
  FROM stg.S02_CLTE_PN_TXT;

INSERT INTO ods.W1_03_CLTUNIF_TXT
SELECT SUBSTRING(TRAMA,1,15) ,
       SUBSTRING(TRAMA,16,10),
       SUBSTRING(TRAMA,26,3) ,
       SUBSTRING(TRAMA,29,10),
       SUBSTRING(TRAMA,39,3) ,
       SUBSTRING(TRAMA,42,1) ,
       SUBSTRING(TRAMA,43,10),
       SUBSTRING(TRAMA,53,26) 
  FROM stg.S03_CLTUNIF_TXT;

INSERT INTO ods.W1_04_DIRECC_TXT
SELECT SUBSTRING(TRAMA,1,10) ,
       SUBSTRING(TRAMA,11,6) ,
       SUBSTRING(TRAMA,17,150) ,
       SUBSTRING(TRAMA,167,25) ,
       SUBSTRING(TRAMA,192,25) ,
       SUBSTRING(TRAMA,217,25) ,
       SUBSTRING(TRAMA,242,150),
       SUBSTRING(TRAMA,392,1) ,
       SUBSTRING(TRAMA,393,20) ,
       SUBSTRING(TRAMA,413,20) ,
       SUBSTRING(TRAMA,433,1) 
  FROM stg.S04_DIRECC_TXT;

INSERT INTO ods.W1_05_EMAIL_TXT
SELECT SUBSTRING(TRAMA,1,10)   ,
       SUBSTRING(TRAMA,11,100) ,
       SUBSTRING(TRAMA,111,8)
  FROM stg.S05_EMAIL_TXT;

INSERT INTO ods.W1_06_EMANOCON_TXT
SELECT SUBSTRING(TRAMA,1,10)   ,
       SUBSTRING(TRAMA,11,100) ,
       SUBSTRING(TRAMA,111,1)
  FROM stg.S06_EMANOCON_TXT;

INSERT INTO ods.W1_07_HIJOS_TXT
SELECT SUBSTRING(TRAMA,1,10) ,
       SUBSTRING(TRAMA,11,1) ,
       SUBSTRING(TRAMA,12,8)
  FROM stg.S07_HIJOS_TXT;

INSERT INTO ods.W1_08_TARJETA_TXT
SELECT SUBSTRING(TRAMA,1,10)  ,
       SUBSTRING(TRAMA,11,19) ,
       SUBSTRING(TRAMA,30,20)
  FROM stg.S08_TARJETA_TXT;

INSERT INTO ods.W1_09_TELEF_TXT
SELECT SUBSTRING(TRAMA,1,10)  ,
       SUBSTRING(TRAMA,11,10) ,
       SUBSTRING(TRAMA,21,8)
  FROM stg.S09_TELEF_TXT;

INSERT INTO ods.W1_10_TLFNOCON_TXT
SELECT SUBSTRING(TRAMA,1,10)  ,
       SUBSTRING(TRAMA,11,10) ,
       SUBSTRING(TRAMA,21,1) 
  FROM stg.S10_TLFNOCON_TXT;


INSERT INTO ods.W2_01_CLTE_PJ_TXT
SELECT CASE RTRIM(LTRIM(CODIGOPERSONA     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGOPERSONA     )) END,
       CASE RTRIM(LTRIM(CODIGOTIPOPERSONA )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGOTIPOPERSONA )) END,
       CASE RTRIM(LTRIM(TIPODEDOCUMENTO   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(TIPODEDOCUMENTO   )) END,
       CASE RTRIM(LTRIM(NRODOCUMENTO      )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(NRODOCUMENTO      )) END,
       CASE RTRIM(LTRIM(RAZONSOCIAL       )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(RAZONSOCIAL       )) END,
       CASE RTRIM(LTRIM(FECHACREACIONS01  )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FECHACREACIONS01  )) END,
       CASE RTRIM(LTRIM(HORACREACIONS01   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(HORACREACIONS01   )) END,
       CASE RTRIM(LTRIM(FECHAULTMODIFS01  )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FECHAULTMODIFS01  )) END
FROM ods.W1_01_CLTE_PJ_TXT;

INSERT INTO ods.W2_02_CLTE_PN_TXT
SELECT CASE RTRIM(LTRIM(CODIGOPERSONA     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGOPERSONA     )) END,
       CASE RTRIM(LTRIM(CODIGOTIPOPERSONA )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGOTIPOPERSONA )) END,
       CASE RTRIM(LTRIM(TIPODEDOCUMENTO   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(TIPODEDOCUMENTO   )) END,
       CASE RTRIM(LTRIM(NRODOCUMENTO      )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(NRODOCUMENTO      )) END,
       CASE RTRIM(LTRIM(NRORUC            )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(NRORUC            )) END,
       CASE RTRIM(LTRIM(NOMBRES           )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(NOMBRES           )) END,
       CASE RTRIM(LTRIM(APELLIDOPATERNO   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(APELLIDOPATERNO   )) END,
       CASE RTRIM(LTRIM(APELLIDOMATERNO   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(APELLIDOMATERNO   )) END,
       CASE RTRIM(LTRIM(FECHANACIMIENTO   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FECHANACIMIENTO   )) END,
       CASE RTRIM(LTRIM(SEXO_TIT          )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(SEXO_TIT          )) END,
       CASE RTRIM(LTRIM(FLAGESTADOCIVIL   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FLAGESTADOCIVIL   )) END,
       CASE RTRIM(LTRIM(FLAGTIENEHIJOS    )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FLAGTIENEHIJOS    )) END,
       CASE RTRIM(LTRIM(FLAGTIENETELEFONO )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FLAGTIENETELEFONO )) END,
       CASE RTRIM(LTRIM(FLAGTIENECORREO   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FLAGTIENECORREO   )) END,
       CASE RTRIM(LTRIM(FLAGCOMPARTEDATOS )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FLAGCOMPARTEDATOS )) END,
       CASE RTRIM(LTRIM(FLAGAUTCANJE      )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FLAGAUTCANJE      )) END,
       CASE RTRIM(LTRIM(FLAGCLTEFALLECIDO )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FLAGCLTEFALLECIDO )) END,
       CASE RTRIM(LTRIM(FECHACREACIONS02  )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FECHACREACIONS02  )) END,
       CASE RTRIM(LTRIM(HORACREACIONS02   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(HORACREACIONS02   )) END,
       CASE RTRIM(LTRIM(FECHAULTMODIFS02  )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FECHAULTMODIFS02  )) END
FROM ods.W1_02_CLTE_PN_TXT;

INSERT INTO ods.W2_03_CLTUNIF_TXT
SELECT CASE RTRIM(LTRIM(IDPROCESO         )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(IDPROCESO         )) END,
       CASE RTRIM(LTRIM(PERSONAORIGEN     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(PERSONAORIGEN     )) END,
       CASE RTRIM(LTRIM(CUENTAORIGEN      )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CUENTAORIGEN      )) END,
       CASE RTRIM(LTRIM(PERSONADESTINO    )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(PERSONADESTINO    )) END,
       CASE RTRIM(LTRIM(CUENTADESTINO     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CUENTADESTINO     )) END,
       CASE RTRIM(LTRIM(TIPODEOPERACION   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(TIPODEOPERACION   )) END,
       CASE RTRIM(LTRIM(USUARIODEREGISTRO )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(USUARIODEREGISTRO )) END,
       CASE RTRIM(LTRIM(FECHADEREGISTROS03)) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FECHADEREGISTROS03)) END
FROM ods.W1_03_CLTUNIF_TXT;

INSERT INTO ods.W2_04_DIRECC_TXT
SELECT CASE RTRIM(LTRIM(CODIGOPERSONA     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGOPERSONA     )) END,
       CASE RTRIM(LTRIM(CODPOS            )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODPOS            )) END,
       CASE RTRIM(LTRIM(DIRECCION         )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(DIRECCION         )) END,
       CASE RTRIM(LTRIM(DEPARTAMENTO      )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(DEPARTAMENTO      )) END,
       CASE RTRIM(LTRIM(PROVINCIA         )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(PROVINCIA         )) END,
       CASE RTRIM(LTRIM(DISTRITO          )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(DISTRITO          )) END,
       CASE RTRIM(LTRIM(REFERENCIA        )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(REFERENCIA        )) END,
       CASE RTRIM(LTRIM(ESTADO            )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(ESTADO            )) END,
       CASE RTRIM(LTRIM(COORDENADAX       )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(COORDENADAX       )) END,
       CASE RTRIM(LTRIM(COORDENADAY       )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(COORDENADAY       )) END,
       CASE RTRIM(LTRIM(NSE               )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(NSE               )) END
FROM ods.W1_04_DIRECC_TXT;

INSERT INTO ods.W2_05_EMAIL_TXT
SELECT CASE RTRIM(LTRIM(CODIGOPERSONA     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGOPERSONA     )) END,
       CASE RTRIM(LTRIM(EMAILS05          )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(EMAILS05          )) END,
       CASE RTRIM(LTRIM(FECHACREACIONS05  )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FECHACREACIONS05  )) END,
       --ROW_NUMBER() OVER (PARTITION BY CODIGOPERSONA ORDER BY FECHACREACIONS05 DESC, EMAILS05 DESC)
       NULL
FROM ods.W1_05_EMAIL_TXT;

INSERT INTO ods.W2_06_EMANOCON_TXT
SELECT CASE RTRIM(LTRIM(CODIGOPERSONA     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGOPERSONA     )) END,
       CASE RTRIM(LTRIM(EMAILS06          )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(EMAILS06          )) END,
       CASE RTRIM(LTRIM(FLAGCONTACTOS06   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FLAGCONTACTOS06   )) END
FROM ods.W1_06_EMANOCON_TXT;

INSERT INTO ods.W2_07_HIJOS_TXT
SELECT CASE RTRIM(LTRIM(CODIGOPERSONA     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGOPERSONA     )) END,
       CASE RTRIM(LTRIM(SEXO_HIJ          )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(SEXO_HIJ          )) END,
       CASE RTRIM(LTRIM(FECHANACIMIENTO   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FECHANACIMIENTO   )) END
FROM ods.W1_07_HIJOS_TXT;

INSERT INTO ods.W2_08_TARJETA_TXT
SELECT CASE RTRIM(LTRIM(CODIGOPERSONA     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGOPERSONA     )) END,
       CASE RTRIM(LTRIM(NUMTARJETABONUS   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(NUMTARJETABONUS   )) END,
       CASE RTRIM(LTRIM(TIPOTARJETA       )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(TIPOTARJETA       )) END
FROM ods.W1_08_TARJETA_TXT;

INSERT INTO ods.W2_09_TELEF_TXT
SELECT CASE RTRIM(LTRIM(CODIGOPERSONA     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGOPERSONA     )) END,
       CASE RTRIM(LTRIM(TELEFONOS09       )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(TELEFONOS09       )) END,
       CASE RTRIM(LTRIM(FECHACREACIONS09  )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FECHACREACIONS09  )) END,
       --ROW_NUMBER() OVER (PARTITION BY CODIGOPERSONA ORDER BY FECHACREACIONS09 DESC, TELEFONOS09 DESC)
       NULL
FROM ods.W1_09_TELEF_TXT;

INSERT INTO ods.W2_10_TLFNOCON_TXT
SELECT CASE RTRIM(LTRIM(CODIGOPERSONA     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGOPERSONA     )) END,
       CASE RTRIM(LTRIM(TELEFONOS10       )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(TELEFONOS10       )) END,
       CASE RTRIM(LTRIM(FLAGCONTACTOS10   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FLAGCONTACTOS10   )) END
FROM ods.W1_10_TLFNOCON_TXT;

DROP INDEX ods.W3_05_EMAIL_TXT.IX_W3_05_EMAIL_TXT;
DROP INDEX ods.W3_06_EMANOCON_TXT.IX_W3_06_EMANOCON_TXT;
DROP INDEX ods.W3_09_TELEF_TXT.IX_W3_09_TELEF_TXT;
DROP INDEX ods.W3_10_TLFNOCON_TXT.IX_W3_10_TLFNOCON_TXT;

INSERT INTO ods.W3_03_CLTUNIF_TXT  SELECT DISTINCT * FROM ods.W2_03_CLTUNIF_TXT ;
INSERT INTO ods.W3_04_DIRECC_TXT   SELECT DISTINCT * FROM ods.W2_04_DIRECC_TXT  ;
INSERT INTO ods.W3_05_EMAIL_TXT    SELECT DISTINCT * FROM ods.W2_05_EMAIL_TXT   ;
INSERT INTO ods.W3_06_EMANOCON_TXT SELECT DISTINCT * FROM ods.W2_06_EMANOCON_TXT;
INSERT INTO ods.W3_07_HIJOS_TXT    SELECT DISTINCT * FROM ods.W2_07_HIJOS_TXT   ;
INSERT INTO ods.W3_09_TELEF_TXT    SELECT DISTINCT * FROM ods.W2_09_TELEF_TXT   ;
INSERT INTO ods.W3_10_TLFNOCON_TXT SELECT DISTINCT * FROM ods.W2_10_TLFNOCON_TXT;

--logica de telefonos / correos a no contactar
CREATE INDEX IX_W3_05_EMAIL_TXT
ON ods.W3_05_EMAIL_TXT(CODIGOPERSONA, EMAILS05);
CREATE INDEX IX_W3_06_EMANOCON_TXT
ON ods.W3_06_EMANOCON_TXT(CODIGOPERSONA, EMAILS06);
CREATE INDEX IX_W3_09_TELEF_TXT
ON ods.W3_09_TELEF_TXT(CODIGOPERSONA, TELEFONOS09);
CREATE INDEX IX_W3_10_TLFNOCON_TXT
ON ods.W3_10_TLFNOCON_TXT(CODIGOPERSONA, TELEFONOS10);

--email
UPDATE T05
   SET T05.orden = 0
  FROM ods.W3_05_EMAIL_TXT AS T05
         INNER JOIN ods.W3_06_EMANOCON_TXT AS T06
           ON T05.CODIGOPERSONA = T06.CODIGOPERSONA
          AND T05.EMAILS05 = T06.EMAILS06
 WHERE T06.FLAGCONTACTOS06 = 'N';

INSERT INTO ods.W4_05_EMAIL_TXT
SELECT T05.CODIGOPERSONA   ,
       T05.EMAILS05        ,
       T05.FECHACREACIONS05,
       ROW_NUMBER() OVER (PARTITION BY T05.CODIGOPERSONA ORDER BY T05.FECHACREACIONS05 DESC, T05.EMAILS05 DESC)
  FROM ods.W3_05_EMAIL_TXT AS T05
 WHERE T05.orden <> 0;

INSERT INTO ods.W4_05_EMAIL_TXT
SELECT T05.CODIGOPERSONA   ,
       T05.EMAILS05        ,
       T05.FECHACREACIONS05,
       T05.orden
  FROM ods.W3_05_EMAIL_TXT AS T05
 WHERE T05.orden = 0;

--telefono
UPDATE T09
   SET T09.orden = 0
  FROM ods.W3_09_TELEF_TXT AS T09
         INNER JOIN ods.W3_10_TLFNOCON_TXT AS T10
           ON T09.CODIGOPERSONA = T10.CODIGOPERSONA
          AND T09.TELEFONOS09 = T10.TELEFONOS10
 WHERE T10.FLAGCONTACTOS10 = 'N';

INSERT INTO ods.W4_09_TELEF_TXT
SELECT CODIGOPERSONA     ,
       TELEFONOS09       ,
       FECHACREACIONS09  ,
       ROW_NUMBER() OVER (PARTITION BY CODIGOPERSONA ORDER BY FECHACREACIONS09 DESC, TELEFONOS09 DESC)
  FROM ods.W3_09_TELEF_TXT
 WHERE orden <> 0;

INSERT INTO ods.W4_09_TELEF_TXT
SELECT CODIGOPERSONA     ,
       TELEFONOS09       ,
       FECHACREACIONS09  ,
       orden
  FROM ods.W3_09_TELEF_TXT
 WHERE orden = 0;

END
GO