SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [stg].[carga_transacciones]
AS
BEGIN

DECLARE @date NVARCHAR(8),
		@hora NVARCHAR(8);

SET @date = (select date from ctl.wrk01);
SET @hora = (select hora from ctl.wrk02);

--truncates

TRUNCATE TABLE stg.S51_TAAAMMDD_CWN  ;
TRUNCATE TABLE stg.S52_TCAAMMDD_CWN  ;
TRUNCATE TABLE stg.S53_TDAAMMDD_CWN  ;

TRUNCATE TABLE stg.S51_TAAAMMDD  ;
TRUNCATE TABLE stg.S52_TCAAMMDD  ;
TRUNCATE TABLE stg.S53_TDAAMMDD  ;

--ods trx
TRUNCATE TABLE ods.W1_51_TAAAMMDD_CWN;
TRUNCATE TABLE ods.W1_52_TCAAMMDD_CWN;
TRUNCATE TABLE ods.W1_53_TDAAMMDD_CWN;

TRUNCATE TABLE ods.W2_51_TAAAMMDD_CWN;
TRUNCATE TABLE ods.W2_52_TCAAMMDD_CWN;
TRUNCATE TABLE ods.W2_53_TDAAMMDD_CWN;

TRUNCATE TABLE ods.W3_51_TAAAMMDD_CWN;
TRUNCATE TABLE ods.W3_52_TCAAMMDD_CWN;
TRUNCATE TABLE ods.W3_53_TDAAMMDD_CWN;

TRUNCATE TABLE ods.W4_51_TAAAMMDD_CWN;
TRUNCATE TABLE ods.W4_52_TCAAMMDD_CWN;
TRUNCATE TABLE ods.W4_53_TDAAMMDD_CWN;


--inserts transacciones

BULK INSERT stg.S51_TAAAMMDD_CWN FROM 'e:\bi\biclbo\ftp\bandeja\TAYYMMDD.TXT' WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'Char');
BULK INSERT stg.S52_TCAAMMDD_CWN FROM 'e:\bi\biclbo\ftp\bandeja\TCYYMMDD.TXT' WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'Char');
BULK INSERT stg.S53_TDAAMMDD_CWN FROM 'e:\bi\biclbo\ftp\bandeja\TDYYMMDD.TXT' WITH (CODEPAGE = 'ACP', DATAFILETYPE = 'Char');


--ini crea tabla c/filename

--algoritmo que adiciona el filename en la tabla como columna (revisar posibles mejoras)

DECLARE 
    @trama VARCHAR(181), 
    @dummy VARCHAR(58),
    @tempo VARCHAR(58);

--TA
    SET @trama = NULL;
    SET @dummy = NULL;
    SET @tempo = NULL;

DECLARE cursor_S51 CURSOR
  FOR SELECT trama FROM stg.S51_TAAAMMDD_CWN;

OPEN cursor_S51;

    FETCH cursor_S51 INTO @trama;

    SET @dummy = SUBSTRING ( @trama ,1 , 58 );
    SET @tempo = @dummy;

    WHILE (@@FETCH_STATUS = 0)

    BEGIN

            IF SUBSTRING ( @trama ,1 , 1 ) = 'F'
                BEGIN
                    SET @dummy = SUBSTRING ( @trama ,1 , 58 );
                    SET @tempo = @dummy;
                END;
            ELSE
                BEGIN
                    SET @dummy = @tempo;
                END;

            INSERT INTO stg.S51_TAAAMMDD (dummy, trama) VALUES (@dummy, @trama);

        FETCH NEXT FROM cursor_S51 INTO @trama;
    END

CLOSE cursor_S51;

DEALLOCATE cursor_S51;

--TC
    SET @trama = NULL;
    SET @dummy = NULL;
    SET @tempo = NULL;

DECLARE cursor_S52 CURSOR
  FOR SELECT trama FROM stg.S52_TCAAMMDD_CWN;

OPEN cursor_S52;

    FETCH cursor_S52 INTO @trama;

    SET @dummy = SUBSTRING ( @trama ,1 , 58 );
    SET @tempo = @dummy;

    WHILE (@@FETCH_STATUS = 0)

    BEGIN

            IF SUBSTRING ( @trama ,1 , 1 ) = 'F'
                BEGIN
                    SET @dummy = SUBSTRING ( @trama ,1 , 58 );
                    SET @tempo = @dummy;
                END;
            ELSE
                BEGIN
                    SET @dummy = @tempo;
                END;

            INSERT INTO stg.S52_TCAAMMDD (dummy, trama) VALUES (@dummy, @trama);

        FETCH NEXT FROM cursor_S52 INTO @trama;
    END

CLOSE cursor_S52;

DEALLOCATE cursor_S52;

--TD
    SET @trama = NULL;
    SET @dummy = NULL;
    SET @tempo = NULL;

DECLARE cursor_S53 CURSOR
  FOR SELECT trama FROM stg.S53_TDAAMMDD_CWN;

OPEN cursor_S53;

    FETCH cursor_S53 INTO @trama;

    SET @dummy = SUBSTRING ( @trama ,1 , 58 );
    SET @tempo = @dummy;

    WHILE (@@FETCH_STATUS = 0)

    BEGIN

            IF SUBSTRING ( @trama ,1 , 1 ) = 'F'
                BEGIN
                    SET @dummy = SUBSTRING ( @trama ,1 , 58 );
                    SET @tempo = @dummy;
                END;
            ELSE
                BEGIN
                    SET @dummy = @tempo;
                END;

            INSERT INTO stg.S53_TDAAMMDD (dummy, trama) VALUES (@dummy, @trama);

        FETCH NEXT FROM cursor_S53 INTO @trama;
    END

CLOSE cursor_S53;

DEALLOCATE cursor_S53;

--fin crea tabla c/filename


INSERT INTO ods.W1_51_TAAAMMDD_CWN
SELECT SUBSTRING(TRAMA,1,7)  ,
       SUBSTRING(TRAMA,8,50) ,
       SUBSTRING(DUMMY,7,LEN(DUMMY)-7)
  FROM stg.S51_TAAAMMDD
 WHERE LEN(TRAMA) > 0
   AND DUMMY <> TRAMA;

INSERT INTO ods.W1_52_TCAAMMDD_CWN
SELECT SUBSTRING(TRAMA,1,4)  ,
       SUBSTRING(TRAMA,5,4)  ,
       SUBSTRING(TRAMA,9,19) ,
       SUBSTRING(TRAMA,28,8) ,
       SUBSTRING(TRAMA,36,8) ,
       SUBSTRING(TRAMA,44,6) ,
       SUBSTRING(TRAMA,50,6) ,
       SUBSTRING(TRAMA,56,15),
       SUBSTRING(TRAMA,71,1) ,
       SUBSTRING(TRAMA,72,15),
       SUBSTRING(TRAMA,87,1) ,
       SUBSTRING(TRAMA,88,8) ,
       SUBSTRING(TRAMA,96,7) ,
       SUBSTRING(TRAMA,103,10) ,
       SUBSTRING(TRAMA,113,50) ,
       SUBSTRING(TRAMA,163,18) ,
       SUBSTRING(DUMMY,7,LEN(DUMMY)-7)
  FROM stg.S52_TCAAMMDD
 WHERE LEN(TRAMA) > 0
   AND DUMMY <> TRAMA;

INSERT INTO ods.W1_53_TDAAMMDD_CWN
SELECT SUBSTRING(TRAMA,1,18)  ,
       SUBSTRING(TRAMA,19,3)  ,
       SUBSTRING(TRAMA,22,14) ,
       SUBSTRING(TRAMA,36,9)  ,
       SUBSTRING(TRAMA,45,15) ,
       SUBSTRING(TRAMA,60,1)  ,
       SUBSTRING(DUMMY,7,LEN(DUMMY)-7)
  FROM stg.S53_TDAAMMDD
 WHERE LEN(TRAMA) > 0
   AND DUMMY <> TRAMA;


INSERT INTO ods.W2_51_TAAAMMDD_CWN
SELECT CASE RTRIM(LTRIM(CODIGODEPROMOCION )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGODEPROMOCION )) END,
       CASE RTRIM(LTRIM(DESCRIPCIONS51    )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(DESCRIPCIONS51    )) END,
       CASE RTRIM(LTRIM(ARCHIVOORIGEN     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(ARCHIVOORIGEN     )) END
FROM ods.W1_51_TAAAMMDD_CWN;

INSERT INTO ods.W2_52_TCAAMMDD_CWN
SELECT CASE RTRIM(LTRIM(CODIGODEPARTICIPANTE )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGODEPARTICIPANTE )) END,
       CASE RTRIM(LTRIM(CODIGODELOCAL        )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGODELOCAL        )) END,
       CASE RTRIM(LTRIM(NUMTARJETABONUS      )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(NUMTARJETABONUS      )) END,
       CASE RTRIM(LTRIM(FECHATRANSACCIONS02  )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FECHATRANSACCIONS02  )) END,
       CASE RTRIM(LTRIM(HORATRANSACCIONS02   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(HORATRANSACCIONS02   )) END,
       CASE RTRIM(LTRIM(NROPOS               )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(NROPOS               )) END,
       CASE RTRIM(LTRIM(NROTRNPOS            )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(NROTRNPOS            )) END,
       CASE RTRIM(LTRIM(MONTOTOTAL           )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(MONTOTOTAL           )) END,
       CASE RTRIM(LTRIM(SIGNO_MT             )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(SIGNO_MT             )) END,
       CASE RTRIM(LTRIM(PTOSACUMULADOS       )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(PTOSACUMULADOS       )) END,
       CASE RTRIM(LTRIM(SIGNO_PA             )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(SIGNO_PA             )) END,
       CASE RTRIM(LTRIM(FECHAASIGNACIONS52   )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(FECHAASIGNACIONS52   )) END,
       CASE RTRIM(LTRIM(CODIGODEPROMOCION    )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CODIGODEPROMOCION    )) END,
       CASE RTRIM(LTRIM(TIPODETRANSACCION    )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(TIPODETRANSACCION    )) END,
       CASE RTRIM(LTRIM(NOMBREDEALER         )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(NOMBREDEALER         )) END,
       CASE RTRIM(LTRIM(IDTRX                )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(IDTRX                )) END,
       CASE RTRIM(LTRIM(ARCHIVOORIGEN     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(ARCHIVOORIGEN           )) END
FROM ods.W1_52_TCAAMMDD_CWN;

INSERT INTO ods.W2_53_TDAAMMDD_CWN
SELECT CASE RTRIM(LTRIM(IDTRX              )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(IDTRX              )) END,
       CASE RTRIM(LTRIM(SEC                )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(SEC                )) END,
       CASE RTRIM(LTRIM(PLU                )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(PLU                )) END,
       CASE RTRIM(LTRIM(CANTIDAD           )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(CANTIDAD           )) END,
       CASE RTRIM(LTRIM(MONTOPARCIAL       )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(MONTOPARCIAL       )) END,
       CASE RTRIM(LTRIM(SIGNO_MP           )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(SIGNO_MP           )) END,
       CASE RTRIM(LTRIM(ARCHIVOORIGEN     )) WHEN '' THEN NULL ELSE RTRIM(LTRIM(ARCHIVOORIGEN       )) END
FROM ods.W1_53_TDAAMMDD_CWN;


INSERT INTO ods.W3_51_TAAAMMDD_CWN
SELECT DISTINCT
       CODIGODEPROMOCION,
       DESCRIPCIONS51,
       ARCHIVOORIGEN
  FROM ods.W2_51_TAAAMMDD_CWN;

INSERT INTO ods.W3_52_TCAAMMDD_CWN
SELECT DISTINCT
       CODIGODEPARTICIPANTE,
       CODIGODELOCAL       ,
       NUMTARJETABONUS     ,
       FECHATRANSACCIONS02 ,
       HORATRANSACCIONS02  ,
       NROPOS              ,
       NROTRNPOS           ,
       MONTOTOTAL          ,
       SIGNO_MT            ,
       PTOSACUMULADOS      ,
       SIGNO_PA            ,
       FECHAASIGNACIONS52  ,
       CODIGODEPROMOCION   ,
       TIPODETRANSACCION   ,
       NOMBREDEALER        ,
       IDTRX               ,
       ARCHIVOORIGEN
  FROM ods.W2_52_TCAAMMDD_CWN;

INSERT INTO ods.W3_53_TDAAMMDD_CWN
SELECT DISTINCT
       IDTRX       ,
       SEC         ,
       PLU         ,
       CANTIDAD    ,
       MONTOPARCIAL,
       SIGNO_MP    ,
       ARCHIVOORIGEN
  FROM ods.W2_53_TDAAMMDD_CWN;


DROP INDEX ods.W4_51_TAAAMMDD_CWN.IX1_W4_51_TAAAMMDD_CWN;
DROP INDEX ods.W4_52_TCAAMMDD_CWN.IX1_W4_52_TCAAMMDD_CWN;
DROP INDEX ods.W4_52_TCAAMMDD_CWN.IX2_W4_52_TCAAMMDD_CWN;
DROP INDEX ods.W4_53_TDAAMMDD_CWN.IX1_W4_53_TDAAMMDD_CWN;

INSERT INTO ods.W4_51_TAAAMMDD_CWN
SELECT T1.CODIGODEPROMOCION,
       T1.DESCRIPCIONS51,
       T1.MAXAO
  FROM (SELECT CODIGODEPROMOCION,
               DESCRIPCIONS51,
               MAX(ARCHIVOORIGEN) AS MAXAO
          FROM ods.W3_51_TAAAMMDD_CWN
         GROUP BY CODIGODEPROMOCION,
               DESCRIPCIONS51) AS T1
       INNER JOIN
       (SELECT CODIGODEPROMOCION,
               MAX(ARCHIVOORIGEN) AS MAXAO
          FROM ods.W3_51_TAAAMMDD_CWN
         GROUP BY CODIGODEPROMOCION) AS T2
       ON T1.CODIGODEPROMOCION = T2.CODIGODEPROMOCION AND T1.MAXAO = T2.MAXAO
 ORDER BY T1.CODIGODEPROMOCION;

INSERT INTO ods.W4_52_TCAAMMDD_CWN
SELECT CODIGODEPARTICIPANTE,
       CODIGODELOCAL       ,
       NUMTARJETABONUS     ,
       FECHATRANSACCIONS02 ,
       HORATRANSACCIONS02  ,
       NROPOS              ,
       NROTRNPOS           ,
       MONTOTOTAL          ,
       SIGNO_MT            ,
       PTOSACUMULADOS      ,
       SIGNO_PA            ,
       FECHAASIGNACIONS52  ,
       CODIGODEPROMOCION   ,
       TIPODETRANSACCION   ,
       NOMBREDEALER        ,
       IDTRX               ,
       MAX(ARCHIVOORIGEN)
  FROM ods.W3_52_TCAAMMDD_CWN
 WHERE NUMTARJETABONUS <> '0000000000000000000'
 GROUP BY CODIGODEPARTICIPANTE,
       CODIGODELOCAL       ,
       NUMTARJETABONUS     ,
       FECHATRANSACCIONS02 ,
       HORATRANSACCIONS02  ,
       NROPOS              ,
       NROTRNPOS           ,
       MONTOTOTAL          ,
       SIGNO_MT            ,
       PTOSACUMULADOS      ,
       SIGNO_PA            ,
       FECHAASIGNACIONS52  ,
       CODIGODEPROMOCION   ,
       TIPODETRANSACCION   ,
       NOMBREDEALER        ,
       IDTRX;

INSERT INTO ods.W4_53_TDAAMMDD_CWN
SELECT IDTRX       ,
       SEC         ,
       PLU         ,
       CANTIDAD    ,
       MONTOPARCIAL,
       SIGNO_MP    ,
       MAX(ARCHIVOORIGEN)
  FROM ods.W3_53_TDAAMMDD_CWN
 WHERE IDTRX <> '000000000000000000'
 GROUP BY IDTRX    ,
       SEC         ,
       PLU         ,
       CANTIDAD    ,
       MONTOPARCIAL,
       SIGNO_MP;

CREATE INDEX IX1_W4_51_TAAAMMDD_CWN ON ods.W4_51_TAAAMMDD_CWN(CODIGODEPROMOCION);
CREATE INDEX IX1_W4_52_TCAAMMDD_CWN ON ods.W4_52_TCAAMMDD_CWN(CODIGODEPROMOCION);
CREATE INDEX IX2_W4_52_TCAAMMDD_CWN ON ods.W4_52_TCAAMMDD_CWN(IDTRX);
CREATE INDEX IX1_W4_53_TDAAMMDD_CWN ON ods.W4_53_TDAAMMDD_CWN(IDTRX);


--historias
INSERT INTO ctl.H51_TAAAMMDD
SELECT *,
       @date,
       @hora
  FROM ods.W3_51_TAAAMMDD_CWN;

INSERT INTO ctl.H52_TCAAMMDD
SELECT *,
       @date,
       @hora
  FROM ods.W3_52_TCAAMMDD_CWN;

INSERT INTO ctl.H53_TDAAMMDD
SELECT *,
       @date,
       @hora
  FROM ods.W3_53_TDAAMMDD_CWN;

END
GO