CREATE TABLE [bds].[CONTACTO] (
  [CODIGOPERSONA] [varchar](10) NOT NULL,
  [CANAL] [varchar](10) NOT NULL,
  [CONTACTO] [varchar](100) NOT NULL,
  [FLAGCONTACTO_NOC] [varchar](1) NULL,
  [FECHACARGAINICIAL_NOC] [varchar](8) NULL,
  [FECHACARGAULTMODIF_NOC] [varchar](8) NULL,
  CONSTRAINT [PK_B_CONTACTO] PRIMARY KEY CLUSTERED ([CODIGOPERSONA], [CANAL], [CONTACTO])
)
ON [PRIMARY]
GO

CREATE INDEX [IX1_B_CONTACTO]
  ON [bds].[CONTACTO] ([CODIGOPERSONA], [CANAL])
  ON [PRIMARY]
GO