CREATE TABLE [bds].[TABLON_MKT] (
  [ANO] [varchar](4) NULL,
  [MES] [varchar](2) NULL,
  [RE_UNDECO] [varchar](60) NULL,
  [CANT] [int] NULL,
  [CODIGOTIPOPERSONA_D] [varchar](8) NULL,
  [TIPODEDOCUMENTO_D] [varchar](11) NULL,
  [NRODOCUMENTO] [varchar](15) NULL,
  [NRORUC] [varchar](11) NULL,
  [NOMBRES] [varchar](100) NULL,
  [APELLIDOPATERNO] [varchar](50) NULL,
  [APELLIDOMATERNO] [varchar](50) NULL,
  [FECHANACIMIENTO] [varchar](8) NULL,
  [SEXO_TIT_D] [varchar](11) NULL,
  [FLAGESTADOCIVIL_D] [varchar](11) NULL,
  [FLAGTIENEHIJOS_D] [varchar](2) NULL,
  [FLAGTIENETELEFONO_D] [varchar](2) NULL,
  [FLAGTIENECORREO_D] [varchar](2) NULL,
  [FLAGCOMPARTEDATOS_D] [varchar](2) NULL,
  [FLAGAUTCANJE_D] [varchar](2) NULL,
  [FLAGCLTEFALLECIDO_D] [varchar](2) NULL,
  [RAZONSOCIAL] [varchar](50) NULL,
  [CODPOS] [varchar](6) NULL,
  [DIRECCION] [varchar](150) NULL,
  [DEPARTAMENTO] [varchar](25) NULL,
  [PROVINCIA] [varchar](25) NULL,
  [DISTRITO] [varchar](25) NULL,
  [REFERENCIA] [varchar](150) NULL,
  [ESTADO_D] [varchar](6) NULL,
  [COORDENADAX] [varchar](20) NULL,
  [COORDENADAY] [varchar](20) NULL,
  [FLAGCOORDENADA] [varchar](1) NULL,
  [NSE] [varchar](1) NULL,
  [TELEFONO] [varchar](10) NULL,
  [TELEFONO_D] [varchar](10) NULL,
  [FECHACREACION_TEL] [varchar](8) NULL,
  [EMAIL] [varchar](100) NULL,
  [FECHACREACION_EML] [varchar](8) NULL,
  [HIJ_AS] [int] NULL,
  [HIJ_OS] [int] NULL,
  [HIJ_NN] [int] NULL,
  [HIJ_TOT] [int] NULL
)
ON [PRIMARY]
GO