CREATE TABLE [bds].[HIJO] (
  [CODIGOPERSONA] [varchar](10) NOT NULL,
  [SEXO_HIJ] [varchar](1) NOT NULL,
  [FECHANACIMIENTO] [varchar](8) NOT NULL,
  [FECHACARGAINICIAL_HIJ] [varchar](8) NULL,
  [FECHACARGAULTMODIF_HIJ] [varchar](8) NULL,
  CONSTRAINT [PK_B_HIJO] PRIMARY KEY CLUSTERED ([CODIGOPERSONA], [SEXO_HIJ], [FECHANACIMIENTO])
)
ON [PRIMARY]
GO

CREATE INDEX [IX1_B_HIJO]
  ON [bds].[HIJO] ([CODIGOPERSONA])
  ON [PRIMARY]
GO