CREATE TABLE [ods].[W3_05_EMAIL_TXT] (
  [CODIGOPERSONA] [varchar](10) NULL,
  [EMAILS05] [varchar](100) NULL,
  [FECHACREACIONS05] [varchar](8) NULL,
  [orden] [int] NULL
)
ON [PRIMARY]
GO

CREATE INDEX [IX_W3_05_EMAIL_TXT]
  ON [ods].[W3_05_EMAIL_TXT] ([CODIGOPERSONA], [EMAILS05])
  ON [PRIMARY]
GO