CREATE TABLE [ods].[HIJO_E] (
  [CODIGOPERSONA] [varchar](10) NOT NULL,
  [SEXO_HIJ] [varchar](1) NOT NULL,
  [FECHANACIMIENTO] [varchar](8) NOT NULL,
  [FECHACARGAINICIAL_HIJ] [varchar](8) NULL,
  [FECHACARGAULTMODIF_HIJ] [varchar](8) NULL
)
ON [PRIMARY]
GO