CREATE TABLE [ods].[W1_03_CLTUNIF_TXT] (
  [IDPROCESO] [varchar](15) NULL,
  [PERSONAORIGEN] [varchar](10) NULL,
  [CUENTAORIGEN] [varchar](3) NULL,
  [PERSONADESTINO] [varchar](10) NULL,
  [CUENTADESTINO] [varchar](3) NULL,
  [TIPODEOPERACION] [varchar](1) NULL,
  [USUARIODEREGISTRO] [varchar](10) NULL,
  [FECHADEREGISTROS03] [varchar](26) NULL
)
ON [PRIMARY]
GO