CREATE TABLE [ods].[W4_52_TCAAMMDD_CWN] (
  [CODIGODEPARTICIPANTE] [varchar](4) NULL,
  [CODIGODELOCAL] [varchar](4) NULL,
  [NUMTARJETABONUS] [varchar](19) NULL,
  [FECHATRANSACCIONS02] [varchar](8) NULL,
  [HORATRANSACCIONS02] [varchar](8) NULL,
  [NROPOS] [varchar](6) NULL,
  [NROTRNPOS] [varchar](6) NULL,
  [MONTOTOTAL] [varchar](15) NULL,
  [SIGNO_MT] [varchar](1) NULL,
  [PTOSACUMULADOS] [varchar](15) NULL,
  [SIGNO_PA] [varchar](1) NULL,
  [FECHAASIGNACIONS52] [varchar](8) NULL,
  [CODIGODEPROMOCION] [varchar](7) NULL,
  [TIPODETRANSACCION] [varchar](10) NULL,
  [NOMBREDEALER] [varchar](50) NULL,
  [IDTRX] [varchar](18) NULL,
  [ARCHIVOORIGEN] [varchar](58) NULL
)
ON [PRIMARY]
GO

CREATE INDEX [IX1_W4_52_TCAAMMDD_CWN]
  ON [ods].[W4_52_TCAAMMDD_CWN] ([CODIGODEPROMOCION])
  ON [PRIMARY]
GO

CREATE INDEX [IX2_W4_52_TCAAMMDD_CWN]
  ON [ods].[W4_52_TCAAMMDD_CWN] ([IDTRX])
  ON [PRIMARY]
GO