CREATE TABLE [ods].[W3_06_EMANOCON_TXT] (
  [CODIGOPERSONA] [varchar](10) NULL,
  [EMAILS06] [varchar](100) NULL,
  [FLAGCONTACTOS06] [varchar](1) NULL
)
ON [PRIMARY]
GO

CREATE INDEX [IX_W3_06_EMANOCON_TXT]
  ON [ods].[W3_06_EMANOCON_TXT] ([CODIGOPERSONA], [EMAILS06])
  ON [PRIMARY]
GO