CREATE TABLE [ods].[W3_10_TLFNOCON_TXT] (
  [CODIGOPERSONA] [varchar](10) NULL,
  [TELEFONOS10] [varchar](10) NULL,
  [FLAGCONTACTOS10] [varchar](1) NULL
)
ON [PRIMARY]
GO

CREATE INDEX [IX_W3_10_TLFNOCON_TXT]
  ON [ods].[W3_10_TLFNOCON_TXT] ([CODIGOPERSONA], [TELEFONOS10])
  ON [PRIMARY]
GO