CREATE TABLE [ods].[W4_51_TAAAMMDD_CWN] (
  [CODIGODEPROMOCION] [varchar](7) NULL,
  [DESCRIPCIONS51] [varchar](50) NULL,
  [ARCHIVOORIGEN] [varchar](58) NULL
)
ON [PRIMARY]
GO

CREATE INDEX [IX1_W4_51_TAAAMMDD_CWN]
  ON [ods].[W4_51_TAAAMMDD_CWN] ([CODIGODEPROMOCION])
  ON [PRIMARY]
GO